### ISSUE TITLE
sel4test-sim can fail on GH runners

### ISSUE THREAD

**Issue by lsf37** [seL4/ci-actions#112]
On seL4/seL4#449 which does not change the binary (checked that by comparing said binaries), we saw the PC99_debug_clang_64 simulation test failing. It succeeded after re-running.

The specific test task that failed was `Running test SCHED0021 (Test for pre-emption during running of many threads with equal prio)`, which depends on timer input.

It looks like that can be too unreliable on GitHub.

Just putting this information here in case we're seeing this more often. If we do we might either have to remove this test from simulation, or tweak parameters to make occurrence rare enough that it is not a nuisance.

**Comment by axel-h** [comment]
I can confirm that we are also seein SCHED0021 fail on various QEMU platform in out CI system. So it is not a Github issue.

**Comment by axel-h** [comment]
Seems SCHED0021 is als suffering from a race condition. The threads are release and a `yield()` is called. It might happen that the round robin scheduler preempts the main thread after it released the other threads (by clearing the global variable), but before is can call `yield()`. In this case all threads can run 2 time slices and not just one.

**Comment by lsf37** [comment]
This is now tracked in seL4/sel4test#42
