### ISSUE TITLE
l4v proof testboard should filter by architecture

### ISSUE THREAD

**Issue by lsf37** [seL4/ci-actions#176]
The current testboard implementation always runs the proofs for all `L4V_ARCH`. Instead, it should run only the list of architectures requested in the commit message.

This will need some refactoring of the management code for the test board.

**Comment by axel-h** [comment]
I wonder if trying to automatically detect the targets that are impacted by a change is possible? Using manual tags might not catch the subtle things. There is a price because some source or binary diff requires assembling the thing to diff - but that might be cheap compared to the proof run.

**Comment by lsf37** [comment]
Ah, I should have been more precise. Context is difficult :-) This issue is for a different testboard -- it's for when you have changed the proof and want to do a test run on your changes before you make a PR. This is esp useful if you're working from a fairly limited machine.

For testing C changes, I agree it's not a good idea to test these manually. We could try to figure out from preprocess results which images need testing, but it's often enough all or none that it doesn't matter so much in terms of VM limits. (Whereas for proof changes you might want to run a few of these)

**Comment by lsf37** [comment]
I'm closing this, because with the AWS PR tests we now have, the testboard has become essentially unused.
