### ISSUE TITLE
Investigate running MCS on Qemu simulation targets

### ISSUE THREAD

**Issue by kent-mcleod** [seL4/ci-actions#188]
(Imported form https://sel4.atlassian.net/browse/SELFOUR-2377)

simulation sel4test builds don't run any MCS configurations.  Historically this was because of many of the tests are time sensitive and don't handle Qemu's emulation of time very well.

**Comment by lsf37** [comment]
This is more an issue for sel4test -- once it supports simulation builds for MCS, they are easy to switch on for CI.

**Comment by axel-h** [comment]
Can we close this issue here, as https://github.com/seL4/sel4test/issues/72 is main task now?

**Comment by lsf37** [comment]
Happy to close this one for now, to be re-opened when the upstream issue is done.
