### ISSUE TITLE
ARM_MCS_verified.cmake not used by CI when running seL4/ci-actions/standalone-kernel

### ISSUE THREAD

**Issue by axel-h** [seL4/ci-actions#294]
`seL4/ci-actions/standalone-kernel` runs `/configs/ARM_verified.cmake` for both MCS and non-MCS. I wonder, shouldn't `ARM_MCS_verified.cmake` be used in this case?

**Comment by lsf37** [comment]
You're right, the standalone compile test probably predates `ARM_MCS_verified.cmake`.

The complication is that we want MCS tested for all architectures, but verified configs only exist for ARM and RISCV64. Could still test for the existence of the `MCS` file and prefer that when it's there.

**Comment by axel-h** [comment]
Fixed with the PR merge.
