### ISSUE TITLE
upgrade actions to Node 20

### ISSUE THREAD

**Issue by lsf37** [seL4/ci-actions#320]
GitHub has started to produce warnings for Node 16 actions. See also <https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/>.

Should hopefully just be a matter of dependency update.

**Comment by axel-h** [comment]
In my CI tests I added a patch with this update, and it seems to work for what the runs cover. I have not made a PR because I was unsure about the other workflows. Is there anything specific we should test?

**Comment by lsf37** [comment]
There's no good way to test them all. I'd say we do the dependency update and revert if anything breaks.

**Comment by lsf37** [comment]
I'll have a look at that now

**Comment by lsf37** [comment]
Doing #321 first, so we don't have to update that one as well.
