### ISSUE TITLE
Dockerhub still advertises obsolete trustworthysystems/sel4-riscv

### ISSUE THREAD

**Issue by axel-h** [seL4/ci-actions#336]
Not sure if this is the right place to raise this, but when opening https://hub.docker.com/r/trustworthysystems/sel4 it still mentions the obsolete container `trustworthysystems/sel4-riscv`. It go the last update over 2 years ago. Similar for https://hub.docker.com/r/trustworthysystems/camkes it mentions `trustworthysystems/camkes-riscv` and `trustworthysystems/camkes-cakeml-cogent-riscv-rust`, which also have not recieved any update in the last tow years

I think the pages should be update to just mention the currently maintained container. And the dedicated RISC-V container should show on their landing page a message that they are deprecated. 

I also wonder, will all these containers move to https://hub.docker.com/u/sel4 eventually?

**Comment by lsf37** [comment]
The descriptions for all repos are now updated so that they say they are unsupported and/or point to the maintained image variations.

The docker seL4 account is separate to avoid spamming the main account with all of the GitHub CI images that won't be useful for normal users.
