### ISSUE TITLE
vm_minimal_sim run failure is not reported

### ISSUE THREAD

**Issue by axel-h** [seL4/ci-actions#339]
The build of `vm_minimal_sim` also runs the QEMU simulation as part opf the build job. Unfortunately, failures there are not reported. While the script clearly expects `buildroot login:` and this never comes, it seems this does not return an error? A quick look at the framkework seems to handle errors:
- https://github.com/seL4/ci-actions/blob/master/camkes-vm/build.py#L42-L45
- `run_build_script()` at https://github.com/seL4/ci-actions/blob/master/seL4-platforms/builds.py#L609-L612

For a run that should have see for example https://github.com/seL4/camkes-vm/actions/runs/4714879145/jobs/8361496520?pr=81
```
-----------[ start test vm_minimal_sim ]-----------
  +++ ../init-build.sh -DAARCH64=TRUE -DPLATFORM=qemu-arm-virt -DCAMKES_VM_APP=vm_minimal
...
  -- Generating done
  -- Build files have been written to: /github/workspace/build
  +++ ninja
  [1/407] Generating capdl/capdl-loader-app/gen_config/capdl_loader_app/platform_info.h
...
  [407/407] Generating images/capdl-loader-image-arm-qemu-arm-virt
  +++ tar czf ../vm_minimal_sim-images.tar.gz images/
  +++ bash -c expect -c 'spawn ./simulate; set timeout [3000](https://github.com/seL4/camkes-vm/actions/runs/4714879145/jobs/8361496520?pr=81#step:3:3004); expect "buildroot login:"'
  spawn ./simulate
  ./simulate: qemu-system-aarch64 -machine virt,virtualization=on,highmem=off,secure=off -cpu cortex-a53 -nographic  -m size=2048  -kernel images/capdl-loader-image-arm-qemu-arm-virt
  ELF-loader started on CPU: ARM Ltd. Cortex-A53 r0p4
...  
  Bootstrapping kernel
...  
  Booting all finished, dropped to user space
...  
  FAULT HANDLER: data fault from vm0.vm0_0_control (ID 0x2) on address 0x90, pc = 0x464014, fsr = 0x93800006
...
  -----------[ end test vm_minimal_sim ]-----------
vm_minimal_sim succeeded
```

**Comment by wom-bat** [comment]
The `simulate` scriupt is doing what it's meant to; but the test needs to look at the output and check it's getting to guetst userspace

**Comment by lsf37** [comment]
Result of further investigation: the `expect` command we've been using for the simulate script will always return exit code `0`, so will never fail. This goes back to bamboo times already, so who knows how many failures have been masked by it in the past (although hw runs will show them, so probably fine after all).

The main thing that is needed is to add a `timeout` pattern to `expect`, eg. something like 

```
expect {
  timeout {exit 1}
  "{success}" {exit 0}
}'
```

**Comment by lsf37** [comment]
The reason the simulation scripts have worked in sel4test is that we also parse the output of the test itself into junit format and detect errors that way. For simulation runs that only wait for the success string, that step is missing.

**Comment by lsf37** [comment]
Reopening, because the issue still persists after #340. In fact, now sel4test-sim takes much longer, because it always is hitting the timeout, even in the success case, and camkes-vm-examples is still failing + hitting the timeout.

Need to investigate more.

**Comment by wom-bat** [comment]
I think the problem now is the lack of a success criterion in the build.yaml

**Comment by lsf37** [comment]
I think I have it now. I got the syntax slightly wrong, it should be:

```sh
expect -c "spawn ./simulate; set timeout XX; expect \"good output\" {exit 0} \"bad output\" {exit 1} timeout {exit 1}"
```

and I had:

```sh
expect -c "spawn ./simulate; set timeout XX; expect { \"good output\" {exit 0} \"bad output\" {exit 1} timeout {exit 1} }"
```

That additional pair or braces made everything an action, and the `expect` part was basically empty. Will put up a PR.

**Comment by lsf37** [comment]
This now appears to be working properly and also fails fast when the known error string is detected.
