### ISSUE TITLE
ssrg-bamboo `test` and ssrg-bamboo `proof` actions don't seem to be working

### ISSUE THREAD

**Issue by kent-mcleod** [seL4/ci-actions#68]

**Comment by kent-mcleod** [comment]
https://github.com/seL4/seL4/pull/381#issuecomment-864343032

**Comment by lsf37** [comment]
@nomadeel could you please have a look at what's wrong with the bot next week? I don't have access any more. (Happy to help)

**Comment by kent-mcleod** [comment]
Also https://github.com/seL4/seL4/pull/365#issuecomment-857261872

**Comment by nomadeel** [comment]
Taking a look now.

**Comment by nomadeel** [comment]
Seems like the docker container for the bot was never run, I'll try deploying it on the TS Bamboo VM and see if it works.

**Comment by kent-mcleod** [comment]
Also https://github.com/seL4/seL4/pull/409#issuecomment-865465604

**Comment by nomadeel** [comment]
I think I have it running now, let me test it out now.

**Comment by nomadeel** [comment]
Looks like it's working? https://github.com/seL4/seL4/pull/409#issuecomment-865609578

**Comment by lsf37** [comment]
Yes! Very nice.

**Comment by lsf37** [comment]
Let's see if it also reports results, but when it does we can close here. It has nicely remembered all the missed invocations, it seems.

**Comment by kent-mcleod** [comment]
No results have been reported yet.

**Comment by lsf37** [comment]
Yeah, not a good sign. @nomadeel did say there was a huge Bamboo backlog, so something might have gotten stuck somewhere.

**Comment by nomadeel** [comment]
It's working, just that the results are now in the checks section instead of being reported via a comment.

**Comment by lsf37** [comment]
> It's working, just that the results are now in the checks section instead of being reported via a comment.

The bot should still be responding, though. So the tests kicked off correctly, and it's running on Bamboo (which makes it show up in status), but the bot is not picking up on completed tests (or for the proofs not responding at all). Does the bot log file say anything enlightening?

**Comment by kent-mcleod** [comment]
The bot still doesn't seem to be working: https://github.com/seL4/seL4/pull/381#issuecomment-869539171

**Comment by lsf37** [comment]
It looks like the bot works again.

With the sel4sim action, the `ssrg-bot test` should now not be necessary any more. I'll have a look at an AWS setup from GitHub for the proofs today and tomorrow. It'll take a bit longer than that to switch everything to that, including the proof testboard, but when we are there, we should be able to retire the bot.
