### ISSUE TITLE
sel4test compile action

### ISSUE THREAD

**Issue by lsf37** [seL4/ci-actions#73]
Not entirely clear if we want this.

On bamboo we had this for all PRs. I would actually prefer to go one step further on PRs and automatically run all of the simulation tests (but trigger hardware tests manually).

**Comment by axel-h** [comment]
I think this makes sense.

**Comment by pingerino** [comment]
As long as simulation doesn't try and run if the kernel doesn't compile. This is why we staged it. Also not all targets are simulate-able, but we want to make sure they compile.

**Comment by lsf37** [comment]
> As long as simulation doesn't try and run if the kernel doesn't compile. This is why we staged it. Also not all targets are simulate-able, but we want to make sure they compile.

Bamboo currently has 4 stages, 2 for simulation targets (build + simulate) and 2 for hardware targets (build + simulate). The idea would be to fuse the build and run stage for simulate, but not hardware, i.e.:

- if armv7-simulate build does not work, it won't try to simulate, but if the armv8-simulate build succeeded for the same kernel, it would simulate that one.
- if any simulate run (or build) didn't work, the HW test would not trigger unless started manually

For the hardware test we probably want to keep it staged as we have it on Bamboo to keep down the load on the machine queue, i.e. it should only run any actual hardware test if all of the hardware builds succeeded.
