### ISSUE TITLE
docker deploy action

### ISSUE THREAD

**Issue by lsf37** [seL4/ci-actions#85]
For the [seL4-CAmkES-L4v-dockerfiles](https://github.com/seL4/seL4-CAmkES-L4v-dockerfiles) repo, after build (#84), on push to the master branch, deploy a set of images.

The action can probably go into that repo directly.

List of images to deploy.

  - [x] CakeMLToolchain
  - [x] Camkes
  - [x] L4v
  - RISCV (no longer a separate image)
  - [x] seL4
  - Sysinit (unmaintained)
  - Other:
    - [x] sel4-rust
    - camkes-vis (unmaintained)
    - l4v-cakeml (unmaintained)
    - rust-sysinit (no longer a separate image)

**Comment by lsf37** [comment]
Also blocked on machine-queue, see #84

**Comment by axel-h** [comment]
There seems to be a deploy action now, can this be closed?

**Comment by lsf37** [comment]
No, that action doesn't deploy yet.

**Comment by lsf37** [comment]
(This issue is for the action inside the https://github.com/seL4/seL4-CAmkES-L4v-dockerfiles repo, not the deploy actions in side this repo)

**Comment by lsf37** [comment]
Being implemented in https://github.com/seL4/seL4-CAmkES-L4v-dockerfiles/pull/49

We might want to add a test for each of the images that something actually compiles in them, but let's get them properly deploying first.

**Comment by lsf37** [comment]
The container build already includes a `sel4test` simulation run, so the test I wanted is already there.
