### ISSUE TITLE
action for seL4 releases

### ISSUE THREAD

**Issue by lsf37** [seL4/ci-actions#91]
This includes camkes, l4v, etc.

Currently this is triggered by a nightly run on Bamboo.

This is probably not quite appropriate any more on the GitHub setup (on push to master for specific repos? manually triggered?), and needs some additional thinking on how to avoid race conditions as in the 12.1.0 release, where some repo had new commits before the test finished, and so the release script didn't trigger correctly.

(but otherwise reuse the existing release scripts)

**Comment by lsf37** [comment]
Mostly done for this repo and seL4, but still needs to be deployed in the other main repos, so keeping this open for a bit longer.

**Comment by kent-mcleod** [comment]
> Currently this is triggered by a nightly run on Bamboo.

Apart from the verification-manifests, the other manifest repositories were updated every time a test passed and the nightly triggers were removed because they were too racy I thought.

**Comment by lsf37** [comment]
> Apart from the verification-manifests, the other manifest repositories were updated every time a test passed and the nightly triggers were removed because they were too racy I thought.

That makes sense and is the natural setup for GiHub as well. sel4test and camkes tests currently run that way already and seem to be going fine, so I'll keep with that direction for the rest.

**Comment by lsf37** [comment]
Only one left is the rumprun repo, then I think we have everything the release scripts care about.

Currently, the trigger goes directly from a repo that has changed to the tests for all of the manifests this repo is mentioned in, i.e. they run concurrently instead of in a chain. This seems to be going Ok for now and not be causing too much overload on the machine queue.

I'd be for keeping it this way (unless we run into resource issues), because it avoids a single repo in the chain blocking all other tests.

There is also still the issue we had in the 12.1.0 release that PRs were merged during the release process, so some manifests refer to a different version than others, and the release got stuck because there was not anything consistent to tag. That was resolved manually, but it'd be nice to not have to do that in the future. For 12.1.0 the issue was exacerbated because of networking issues at D61, so the whole thing took much longer than usual. Only way I can see to ensure all release runs see the same state is to not merge PRs just before a release, i.e. have a code freeze period for a few days while everything is churning through.

**Comment by lsf37** [comment]
Ok, all the hardware + deploy actions are done now. seL4 releases should work as before!
